### ISSUE TITLE
Fix buffer reallocation every file when creating GMA file

### ISSUE THREAD

**Issue by FredyH** [Facepunch/gmad#34]
Currently gmad writes the entire GMA file into a ram buffer, before writing it to disk. This is already extremely bad as it means that in the 32 bit version of gmad you cannot reasonably create files bigger than 1GB without running out of ram. There also is no reason to write to ram rather than just writing everything directly to a file.

However, it gets way worse, because the way Bootil's AutoBuffer is used by gmad means that every time a file is written, the buffer has to be reallocated to fit that new file (and the buffer is made no bigger than that). This leads to a quadratic amount of ram being allocated (and free'd directly after) in the number of files in the addon.

This might not sound so bad, so to illustrate I will give some samples, assuming that the average file in an addon is 200KB.

| Addon Size in MB | Total allocated ram  |
|----------|------|
| 10 MB | 250 MB |
| 50 MB | 6.25 GB |
| 100 MB | 25 GB |
| 300 MB |  225 GB |
| 1 GB|  2.5 TB |
| 2 GB | 10 TB |

Yes you read it right, to create a 2 GB GMA file you need to allocate a total of 10 TERABYTES of buffers, and even for a reasonable 300 MB addon, you have to allocate 225 GB throughout the entire creation of the GMA file.

I propose two possible fixes:
1. The most sensible solution would be to bypass ram entirely and just write to the file directly, but I don't think this is something easy to do and requires a lot of code changes.
2. The extremely simple fix would be to just allocate a suitable buffer size. When writing the header to the file, the size of each file is written too. Therefore just sum all of those up, and allocate that much for the buffer.

**Comment by whisperity** [comment]
10 terabytes? Holy hell. For a side-step, perhaps my (now relatively ancient) tool, [SharpGMad](http://github.com/whisperity/SharpGMad) could help. I've not run into memory issues with that even though it's written in C#.

There's a "legacy interface" which is supposed to be a drop-in replacement so it can take normal gmad arguments and works as the original tool does.
