### ISSUE TITLE
Build Warning on Ubuntu Bionic / Debian Buster

### ISSUE THREAD

**Issue by Anticept** [Facepunch/gmad#36]
While testing #35 with Ubuntu Bionic instead, it output this warning, but the build was successful:

`/home/travis/build/wiremod/gmad-build/bootil/projects/linux/gmake/../../../src/Bootil/File/File.cpp:242: warning: the use of `tmpnam' is dangerous, better use `mkstemp'`

**Comment by robotboy655** [comment]
That warning does not come from code in this repo.

https://github.com/garrynewman/bootil
