### ISSUE TITLE
File size cannot be acquired?

### ISSUE THREAD

**Issue by jellyton69** [Facepunch/gmad#38]
When attempting to create a GMA, I receive this error from one of my files: File 'filepath/file.vmt' seems to be empty, or we couldn't get its size! (errno=132)

I have multiple files that are smaller than this one, I'm not sure what the issue could be.

**Comment by robotboy655** [comment]
Please test the gmad.exe on "Dev" beta branch for Garry's Mod and tell me if it still happens.

I can never reproduce this issue.

**Comment by jellyton69** [comment]
Hello Rubat, this issue still occurs on the dev branch.

Here is a link to download the VMT that causes this issue: https://files.jellyton.me/2020/06/shield.vmt

**Comment by robotboy655** [comment]
Well then I don't know what is overflowing on your system. it's something with that file on your PC, uploading it like that doesn't help unfortunately.

**Comment by jellyton69** [comment]
The drive that contains the files I'm trying to upload has a high reallocated sector count, is it possible that the drive itself is causing this issue?

**Comment by jellyton69** [comment]
This was indeed the issue, apologies for the false issue report.
