### ISSUE TITLE
Feature Request: Show ignored files

### ISSUE THREAD

**Issue by ZenBre4ker** [Facepunch/gmad#43]
When creating a gma only chosen files are shown, but ignored ones are not.

The list of chosen files is huge and doesnt really give an overview of the files, that got ignored.
When uploading an addon I made a mistake and ignored "*.md*"-files which includes mdl-files, just because I copied that star from another file-ending.
Didnt notice until a few days later, when the model wasnt available ingame.

Could be a nice addition to make sure in that list are only the files you wanted to ignore ^^

**Comment by robotboy655** [comment]
Handled by https://github.com/Facepunch/gmad/commit/64306882f85d2170227d1b3d3728e58832135658
