### ISSUE TITLE
Official binaries / docker build

### ISSUE THREAD

**Issue by MattJeanes** [Facepunch/gmad#44]
It would be great if there were official binaries we could download or even a docker image

I've created my own here that builds directly from source, but it would be great to have an official one:

https://github.com/MattJeanes/docker-gmad

**Comment by MattJeanes** [comment]
That's true, but I'm thinking more for automated workflows where GMod is not available but you may still want to compress or decompress addons.

My use case in particular is automated workshop publishing from GitHub actions and I didn't really want to download the entirety of GMod with SteamCMD or keep a copy of the executable somewhere to do that.

I've got it all working with my docker version above, but figured it would be worth asking about as I'd rather use a proper official one. Happy for you to close if this is not something you want to do though.

I also just wanted to generally raise awareness of my docker version in case others run into a similar problem to me and they can use mine or use the dockerfile in my repo to build their own version if they don't trust me (which is fair enough).

**Comment by robotboy655** [comment]
Yeah I do not think it's worth it setting up automated builds for this repo at this time, let alone anything docker related.
