### ISSUE TITLE
After December Patch i cant save DamageInfo

### ISSUE THREAD

**Issue by HarionPlayZ** [Facepunch/gmad#47]
i made code like this:

hook.Add("EntityTakeDamage", "Test", function(ent, dmg)
    ent.LastDamageInfo = dmg
end)

when im trying to print dmginfo after some time, i got CTakeDamageInfo [NULL], but not damage info. This error did not exist before the patch.

**Comment by robotboy655** [comment]
This is intentional, you are not supposed to store hook arguments like that. Cache whatever you need in the hook and store that.
